version: '3'
services: 
    app:
        build:
            context: .
            dockerfile: ./src/Dockerfile
        ports: 
            - '8001:80'
        # Para funcionamento no Windows
        tty: true