name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Construição do artefato
        run: docker build .
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
      - name: Login via Azure CLI
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
